num_simul: 10
verbose: true
unknown_trans: false
running_seed: 
init_trans: 
beta: 1.0
mu: 0.01
lam: 1.0
T: 1000
T_warmup: 0
load_env_dir: ./envs
load_env_file_name: dx4_du2_seed42_sigmaSquare0.1
save_dir: ./figures/
save_file_name: known_T{T}_warm{T_warmup}