num_simul: 1
verbose: true
transition: unknown
running_seed: 
init_trans: set_perturb
beta: 1.0
mu: 0.01
lam: 1.0
T: 1000
T_warmup: 100
load_env_dir: ./envs
load_env_file_name: dx4_du2_seed43_sigmaSquare0.1
save_dir: ./figures/
save_file_name: T{T}_warm{T_warmup}_{load_env_file_name}